# Generated by Django 3.2.5 on 2021-07-16 19:13

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Telawa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique=True, verbose_name='title')),
                ('img', models.ImageField(upload_to='images/', verbose_name='img')),
                ('slug', models.SlugField(blank=True, max_length=200, null=True, unique=True, verbose_name='slug')),
                ('updated_on', models.DateTimeField(auto_now=True, verbose_name='updated_on')),
                ('youtube_url', models.TextField(verbose_name='youtube_url')),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='created_on')),
                ('status', models.IntegerField(choices=[(0, 'Draft'), (1, 'Publish')], default=0, verbose_name='status')),
                ('author', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='blog_Telawa', to=settings.AUTH_USER_MODEL, verbose_name='author')),
            ],
            options={
                'verbose_name': 'Telawa',
                'verbose_name_plural': 'Telawas',
                'ordering': ['-created_on'],
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique=True, verbose_name='title')),
                ('slug', models.SlugField(allow_unicode=True, blank=True, max_length=200, null=True, verbose_name='slug')),
                ('img', models.ImageField(upload_to='images/', verbose_name='img')),
                ('updated_on', models.DateTimeField(auto_now=True, verbose_name='updated_on')),
                ('content', ckeditor.fields.RichTextField(verbose_name='content')),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='created_on')),
                ('status', models.IntegerField(choices=[(0, 'Draft'), (1, 'Publish')], default=0, verbose_name='status')),
                ('author', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='blog_posts', to=settings.AUTH_USER_MODEL, verbose_name='author')),
            ],
            options={
                'verbose_name': 'Post',
                'verbose_name_plural': 'posts',
                'ordering': ['-created_on'],
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique=True, verbose_name='title')),
                ('slug', models.SlugField(blank=True, max_length=200, null=True, unique=True, verbose_name='slug')),
                ('img', models.ImageField(upload_to='images/', verbose_name='img')),
                ('writer', models.CharField(max_length=200, unique=True, verbose_name='writer')),
                ('updated_on', models.DateTimeField(auto_now=True, verbose_name='updated_on')),
                ('descrption', models.TextField(verbose_name='descrption')),
                ('file_pdf', models.FileField(upload_to='books/', verbose_name='file_pdf')),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='created_on')),
                ('author', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='blog_books', to=settings.AUTH_USER_MODEL, verbose_name='author')),
            ],
            options={
                'verbose_name': 'Book',
                'verbose_name_plural': 'Books',
                'ordering': ['-created_on'],
            },
        ),
    ]
