# Generated by Django 3.2.5 on 2021-07-15 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_telawa'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='img',
            field=models.ImageField(default='', upload_to='images/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='img',
            field=models.ImageField(default='', upload_to='images/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='telawa',
            name='img',
            field=models.ImageField(default='', upload_to='images/'),
            preserve_default=False,
        ),
    ]
