# Generated by Django 3.2.5 on 2021-07-15 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20210715_1945'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='content',
        ),
        migrations.RemoveField(
            model_name='book',
            name='status',
        ),
        migrations.RemoveField(
            model_name='telawa',
            name='content',
        ),
        migrations.AddField(
            model_name='book',
            name='descrption',
            field=models.TextField(default='', verbose_name='descrption'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='book',
            name='file_pdf',
            field=models.FileField(default='', upload_to='books/', verbose_name='file_pdf'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='book',
            name='writer',
            field=models.CharField(default='', max_length=200, unique=True, verbose_name='writer'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='telawa',
            name='youtube_url',
            field=models.TextField(default='', verbose_name='youtube_url'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='book',
            name='img',
            field=models.ImageField(upload_to='images/', verbose_name='img'),
        ),
        migrations.AlterField(
            model_name='post',
            name='img',
            field=models.ImageField(upload_to='images/', verbose_name='img'),
        ),
        migrations.AlterField(
            model_name='telawa',
            name='img',
            field=models.ImageField(upload_to='images/', verbose_name='img'),
        ),
    ]
